name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      with:
        configuration-path: .github/labels.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
