name: build
on:
  # run on push but only for the develop and release branches
  push:
    branches:
      - main
      - develop
  # run for every pull request
  pull_request: {}
jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Lint and Unit Test
        run: |
          npm run lint
          npm run test
    
      - name: Build and Deploy
        run: |
          npm run build
          npm run deploy
